### PR TITLE
Add keepHtml condition if rowHeaders is true

### PR DESCRIPTION
**Pull request by nightgrey**
Hello micc83,

thank you for your effort in writing this plugin.

I discovered there is no condition for keepHtml if rowHeaders is true, all HTML will be stripped away. Thus I added a condition for this, which IMO was missing and seems unintended. Pretty easy change. What do you say?

Greetings
Nico

### CODE REVIEW

**Comment by micc83** [comment]
Hello @nightgrey,

Sorry if I didn't reply you sooner but I was out on holiday. All I give a look to the PR asap and let you know.

Cheers,
Alessandro

**Comment by micc83** [comment]
Hello @nightgrey can you create a PR to branch [v0.1.2](https://github.com/micc83/ReStable/tree/v0.1.2) as master still hasn't the keepHtml option.

**Comment by nightgrey** [comment]
Sure!

**Comment by micc83** [comment]
Great holidays, already missing Tenerife :smile: 
I'll check your PR asap. Cheers

**Pull request closed without merging**
